### ISSUE TITLE
Cannot import torchquad (conda install)

### ISSUE THREAD

**Issue by theophilec** [esa/torchquad#162]
# Issue
## Problem Description
`import torchquad` fails, throwing a `ModuleNotFoundError` after installing using `conda install torchquad -c conda-forge` (with success).

Python version: 3.8.12
Torchquad version: 0.3.0

```
>>> import torchquad
Traceback (most recent call last):
  File "/Users/tcantelo/miniforge3/envs/causal/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b1a203752725>", line 1, in <module>
    import torchquad
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/tcantelo/miniforge3/envs/causal/lib/python3.8/site-packages/torchquad/__init__.py", line 6, in <module>
    from .integration.integration_grid import IntegrationGrid
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/tcantelo/miniforge3/envs/causal/lib/python3.8/site-packages/torchquad/integration/integration_grid.py", line 6, in <module>
    from .utils import (
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/tcantelo/miniforge3/envs/causal/lib/python3.8/site-packages/torchquad/integration/utils.py", line 18, in <module>
    from utils.set_precision import _get_precision
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'utils.set_precision'; 'utils' is not a package
```

Any help would be appreciated! 😄

**Comment by gomezzz** [comment]
Hey @theophilec !

I just tried creating a new env with 

`mamba create -n tq_import_err python==3.8.12`
`mamba install torchquad -c conda-forge`
on Windows (mamba is like conda just faster, shouldn't matter)

and have no problems.

Can you try creating a new environment with above commands? Maybe something went wrong creating your env?

Alternatively, you could also see if the thing it is trying to import is actually in that folder
`File "/Users/tcantelo/miniforge3/envs/causal/lib/python3.8/site-packages/torchquad/integration/utils.py", line 18, in <module>
    from utils.set_precision import _get_precision`

One more obscure problem could be if you have a function / package or similar defined that is called "utils" that somehow overwrites that import 🤔 In that case I'd be curious about the packages you have in your env / code or other imports you run before the import 🤔

**Comment by theophilec** [comment]
Hi @gomezzz, thanks a lot for your quick reply. In a fresh environment it works fine, and after restarting my IDE I am all good... was a bit quick to open an issue, sorry about that!
